name : Tag Workflow

on: 
  workflow_dispatch:


jobs:
  job1:
    runs-on : ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Execution job 1"

  job2:
    needs: job1
    runs-on : ubuntu-latest
    steps:
      - name: Step 2
        run: echo "Execution job 2"