name: Workflow1

on:
  push:
    branches:
      - main
    tags:
      - tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Execute Python Script
      run: python script.py
