name : Tag Workflow

on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on : ubuntu-latest
    steps:
      - name: Test Model
        env:
          VAR: ${{ vars.VAR1 }}
        run: |
          echo $VAR
          python script.py

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: failure
      if: failure()
      run: |
        echo "le job à échoué"
