name : Tag Workflow

on :
  push:
    tags:
      - 'v*'

jobs:
  job1:
    runs-on : ubuntu-latest
    steps:
      - name: Test Model
        env:
          VAR: ${{ vars.VAR1 }}
        run: |
          echo $VAR