name : Tag Workflow

on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on : ubuntu-latest
    - name: Variables
      env:
        A: 2
        B: 3
    - name: test
      if: ${{A}} > 0 && ${{B}} > 0
      steps:
      - name: afficher les valeurs 
        run: |
          echo "a = $A et b = $B"
