name : Tag Workflow

on: 
  workflow_dispatch:



jobs:
  job1:
    runs-on : ubuntu-latest
    env:
      A: ${{vars.A}}
      B: ${{vars.B}}
    if: $A > 0 && $B > 0
    steps:
    - name: afficher les valeurs 
      run: |
        echo "a = $A et b = $B"