name : Tag Workflow

on: 
  workflow_dispatch:



jobs:
  job1:
    runs-on : ubuntu-latest
    if: ${{vars.A}} > 0 && ${{vars.B}} > 0
    steps:
    - name: afficher les valeurs 
      run: |
        echo "a = ${{vars.B}} et b = ${{vars.B}}"
  
  job2:
    runs-on : ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run code
      run: |
        python multiplication.py