name : Tag Workflow

on :
  push:
    tags:
      - 'release*'
      
jobs:
  job1:
    runs-on : ubuntu-latest
    steps:
      - name: Test Model
        env:
          VAR: ${{ vars.VAR1 }}
        run: |
          echo $VAR

  job2:
    needs: job1
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - name: failure
      run: |
        echo "le job à échoué"
